import "./affine.test.js";
import "./cubic-bezier.test.js";
import "./construction.test.js";
import "./cubic-cubic-discovery.test.js";
import "./cubic-cubic-metamorphic.test.js";
import "./foundation.test.js";
import "./intersection.test.js";
import "./numeric.test.js";
import "./path.test.js";
